version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  vixun:
    image: vixun:latest
    container_name: vixun
    ports:
      - 3000:3000
    environment:
      - MONGODB=VIXUNDB
      - PORT=3000
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - CLOUDINARY_CLOUD_NAME
      - MONGO_URL
      - SESSION_NAME
      - SESSION_SECRET
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
volumes:
  mongodb-data:
    driver: local
